services:
  web:
    image: ${DOCKER_IMAGE:-ts/release-manager-web:latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - VITE_APP_TITLE=${VITE_APP_TITLE:-Release Manager}
    container_name: release-manager-web
    ports:
      - "${SERVER_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
      - API_SERVER_URL=${API_SERVER_URL:-http://localhost:8081}
    restart: unless-stopped
    networks:
      - network-ts

networks:
  network-ts:
    external: true
